# Generated by Django 5.2.13 on 2026-04-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('otchestvo', models.TextField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
                ('module', models.TextField(blank=True, null=True)),
                ('specialization', models.TextField(blank=True, null=True)),
                ('kurs', models.IntegerField(blank=True, null=True)),
                ('group', models.TextField(blank=True, null=True)),
                ('date_begin', models.TextField(blank=True, null=True)),
                ('date_finish', models.TextField(blank=True, null=True)),
                ('head1', models.TextField(blank=True, null=True)),
                ('head2', models.TextField(blank=True, null=True)),
                ('ruc_pract', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fio_genitive', models.TextField(blank=True, null=True)),
                ('module_code', models.TextField(blank=True, null=True)),
                ('tip_title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
    ]
